// Engine Status
export const ENGINE_STARTED = 'ENGINE_STARTED';
export const ENGINE_DEV_STATUS = 'ENGINE_DEV_STATUS';

// Header
export const APP_MAXIMIZE_CHANGE = 'APP_MAXIMIZE_CHANGE';

// Choose Model
export const CLICK_CHOOSE_MODEL_BUTTON = 'CLICK_CHOOSE_MODEL_BUTTON';
export const CHANGE_SELECTED_MODEL = 'CHANGE_SELECTED_MODEL';
