// Engine Status
export const ENGINE_STARTED = 'ENGINE_STARTED';
export const ENGINE_DEV_STATUS = 'ENGINE_DEV_STATUS';

// Header
export const APP_MAXIMIZE_CHANGE = 'APP_MAXIMIZE_CHANGE';

// Choose Model
export const CLICK_CHOOSE_MODEL_BUTTON = 'CLICK_CHOOSE_MODEL_BUTTON';
export const CHANGE_SELECTED_MODEL = 'CHANGE_SELECTED_MODEL';

// Side Menu
export const OPEN_CLOSE_SIDE_MENU = 'OPEN_SIDE_MENU';
export const CHANGE_SELECTED_PAGE = 'CHANGE_SELECTED_PAGE';

// Create Model
export const CREATE_MODEL = 'CREATE_MODEL';

// Choose Dataset for Training
export const CHANGE_SELECTED_DATASET = 'CHOOSE_DATASET_TRAINING';
export const RESET_SELECTED_DATASET = 'RESET_SELECTED_DATASET';

// Delete modals alert dialog
export const OPEN_CLOSE_DELETE_DATASET = 'OPEN_CLOSE_DELETE_DATASET';
export const OPEN_CLOSE_DELETE_LABEL = 'OPEN_CLOSE_DELETE_LABEL';

// Dataset List
export const REFRESH_DATASET_LIST = 'REFRESH_DATASET_LIST';
export const DATASET_LOADING = 'DATASET_LOADING';
export const UPDATE_DATASET_PREVIEW_UPLOAD_FILES = 'UPDATE_DATASET_PREVIEW_UPLOAD_FILES';

// Notifications
export const NOTIFICATION_SEND = 'NOTIFY_SEND';
export const NOTIFICATION_DISMISS = 'NOTIFY_DISMISS';
export const NOTIFICATION_CLEAR = 'NOTIF_CLEAR';

// Active Dataset
export const CHANGE_ACTIVE_DATASET = 'CHANGE_ACTIVE_DATASET';
